//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OESK_Projekt_I.Database.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OESK_NorthwindEntities : DbContext
    {
        public OESK_NorthwindEntities()
            : base("name=OESK_NorthwindEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<CustomerDemographics> CustomerDemographics { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Order_Details> Order_Details { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Shippers> Shippers { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<Territories> Territories { get; set; }
    
        public virtual ObjectResult<Customers> GET_ALL_CUSTOMERS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Customers>("GET_ALL_CUSTOMERS");
        }
    
        public virtual ObjectResult<Customers> GET_ALL_CUSTOMERS(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Customers>("GET_ALL_CUSTOMERS", mergeOption);
        }
    
        public virtual ObjectResult<Customers> GET_CUSTOMERS_WITH_7_IN_PHONE()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Customers>("GET_CUSTOMERS_WITH_7_IN_PHONE");
        }
    
        public virtual ObjectResult<Customers> GET_CUSTOMERS_WITH_7_IN_PHONE(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Customers>("GET_CUSTOMERS_WITH_7_IN_PHONE", mergeOption);
        }
    
        public virtual ObjectResult<GET_COMPANY_AND_BOUGHT_PRODUCT_Result> GET_COMPANY_AND_BOUGHT_PRODUCT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_COMPANY_AND_BOUGHT_PRODUCT_Result>("GET_COMPANY_AND_BOUGHT_PRODUCT");
        }
    
        public virtual ObjectResult<GET_COMPANY_AND_GROUP_PRODUCT_Result> GET_COMPANY_AND_GROUP_PRODUCT()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GET_COMPANY_AND_GROUP_PRODUCT_Result>("GET_COMPANY_AND_GROUP_PRODUCT");
        }
    }
}
